In [6]:
#numpy
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=A+B
D=A-B
E=A*B
F=np.dot(A,B)
A_transpose = A.T
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("addition:")
print(C)
print ("\n substraction")
print(D)
print("\n elementwise multiplication")
print(E)
print("\nmatrix multiplication")
print(F)
print("\n TRANSPOSE;")
print(A_transpose)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
addition:
[[ 6  8]
 [10 12]]

 substraction
[[-4 -4]
 [-4 -4]]

 elementwise multiplication
[[ 5 12]
 [21 32]]

matrix multiplication
[[19 22]
 [43 50]]

 TRANSPOSE;
[[1 3]
 [2 4]]


In [7]:
#svd
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT = np.linalg.svd(X)
n_components = 2
X_reconstructed = np.dot(U[:, :n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("orginal matrix:")
print(X)
print("\n reconstructed matrix (with reduced dimentions):")
print(X_reconstructed)

orginal matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 reconstructed matrix (with reduced dimentions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
